name: cincer2
channels:
  - defaults
dependencies:
  - python=3.8
  - requests
  - matplotlib
  - scipy
  - scikit-learn
  - pandas
  - pip
  - pip:
    - tensorflow==2.4.1
    - tensorflow-probability==0.12.2